<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f5f5f7;margin:0;padding:0;color:#1d1d1f}.wrapper{max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden}.header{background:#34c759;padding:28px 32px;text-align:center}.header h1{color:white;font-size:22px;font-weight:800;margin:0}.body{padding:32px}.greeting{font-size:18px;font-weight:700;margin-bottom:8px}.intro{font-size:14px;color:#6e6e73;line-height:1.6;margin-bottom:24px}.order-box{background:#f0faf4;border-radius:12px;padding:20px;margin-bottom:24px;border-left:3px solid #34c759;text-align:center}.order-val{font-size:22px;font-weight:800;color:#1d1d1f;margin:4px 0}.delivered-badge{display:inline-block;background:#34c759;color:white;font-size:11px;font-weight:700;text-transform:uppercase;padding:4px 12px;border-radius:100px}.invoice-box{background:#f7fafa;border-radius:12px;padding:20px;text-align:center;margin:20px 0;border:2px dashed #008080}.cta-btn{display:inline-block;background:#008080;color:white;text-decoration:none;padding:12px 28px;border-radius:100px;font-weight:700;font-size:14px}.footer{border-top:1px solid #f0f0ec;padding:20px 32px;text-align:center;font-size:12px;color:#6e6e73}.footer a{color:#008080;text-decoration:none}</style></head><body>
<div class="wrapper">
<div class="header"><h1>✓ Order Delivered!</h1></div>
<div class="body">
<div class="greeting">Great news, {{ $order->user->first_name }}!</div>
<p class="intro">Your order has been successfully delivered. Your invoice is now available to download.</p>
<div class="order-box"><div class="order-num" style="font-size:12px;color:#6e6e73;text-transform:uppercase;letter-spacing:.1em;">Order Number</div><div class="order-val">{{ $order->order_number }}</div><span class="delivered-badge">Delivered</span></div>
<div class="invoice-box"><p style="font-size:15px;font-weight:700;color:#1d1d1f;margin-bottom:6px;">📄 Your Invoice is Ready</p><p style="font-size:13px;color:#6e6e73;margin-bottom:14px;">Download your VAT invoice anytime from your account.</p><a href="https://www.ektadigital.co.tz/account" class="cta-btn">Download Invoice</a></div>
</div>
<div class="footer"><strong>Ekta Digital</strong><br/>Haidary Plaza, India Street, Dar-es-Salaam, Tanzania<br/><a href="tel:+255783394445">+255 783 394 445</a> · <a href="mailto:EktaDigital@outlook.com">EktaDigital@outlook.com</a></div>
</div></body></html>
