<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f5f5f7;margin:0;padding:0;color:#1d1d1f}.wrapper{max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.06)}.header{background:#008080;padding:28px 32px;text-align:center}.header h1{color:white;font-size:22px;font-weight:800;margin:0}.header p{color:rgba(255,255,255,.8);font-size:13px;margin:4px 0 0}.body{padding:32px}.greeting{font-size:18px;font-weight:700;margin-bottom:8px}.intro{font-size:14px;color:#6e6e73;line-height:1.6;margin-bottom:24px}.order-box{background:#f7fafa;border-radius:12px;padding:20px;margin-bottom:24px;border-left:3px solid #008080}.order-num{font-size:13px;color:#6e6e73;text-transform:uppercase;letter-spacing:.1em;margin-bottom:4px}.order-val{font-size:20px;font-weight:800;color:#008080}.detail-row{display:flex;justify-content:space-between;font-size:13px;padding:8px 0;border-bottom:1px solid #f0f0ec}.detail-row:last-child{border-bottom:none}.detail-label{color:#6e6e73}.detail-value{font-weight:600}.items-title{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:#6e6e73;margin:24px 0 12px}.item-row{display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid #f0f0ec;font-size:13px}.item-row:last-child{border-bottom:none}.item-name{font-weight:600}.item-qty{color:#6e6e73;font-size:12px}.total-row{display:flex;justify-content:space-between;padding:12px 16px;background:#008080;border-radius:10px;margin-top:12px}.total-label,.total-value{color:white;font-weight:700;font-size:15px}.loyalty-box{background:#fff8e6;border-radius:10px;padding:14px 16px;margin:20px 0;font-size:13px;color:#7c4d00}.cta-btn{display:block;text-align:center;background:#008080;color:white;text-decoration:none;padding:14px 24px;border-radius:100px;font-weight:700;font-size:14px;margin:24px 0 0}.footer{border-top:1px solid #f0f0ec;padding:20px 32px;text-align:center;font-size:12px;color:#6e6e73;line-height:1.7}.footer a{color:#008080;text-decoration:none}</style></head><body>
<div class="wrapper">
<div class="header"><h1>Ekta Digital</h1><p>Digitalise Your Lifestyle</p></div>
<div class="body">
<div class="greeting">Order Confirmed! 🎉</div>
<p class="intro">Hi {{ $order->user->first_name }}, thank you for your order. We've received it and are getting it ready for you.</p>
<div class="order-box"><div class="order-num">Order Number</div><div class="order-val">{{ $order->order_number }}</div></div>
@foreach([['Date',$order->created_at->format('d M Y, H:i')],['Payment',ucfirst(str_replace('_',' ',$order->payment_method))],['Status',ucfirst($order->status)]] as [$label,$value])<div class="detail-row"><span class="detail-label">{{ $label }}</span><span class="detail-value">{{ $value }}</span></div>@endforeach
<div class="items-title">Items Ordered</div>
@foreach($order->items as $item)<div class="item-row"><div><div class="item-name">{{ $item->variant->product->name ?? 'Product' }}</div><div class="item-qty">Qty: {{ $item->quantity }}</div></div><div>TZS {{ number_format($item->line_total_tzs,0) }}</div></div>@endforeach
<div class="total-row"><span class="total-label">Total</span><span class="total-value">TZS {{ number_format($order->total_tzs,0) }}</span></div>
@php $pts=(int)($order->total_tzs/1000); @endphp
@if($pts>0)<div class="loyalty-box">★ You earned <strong>{{ $pts }} loyalty points</strong> (worth TZS {{ number_format($pts*5,0) }})</div>@endif
<a href="https://www.ektadigital.co.tz/account" class="cta-btn">Track My Order</a>
</div>
<div class="footer"><strong>Ekta Digital</strong><br/>Haidary Plaza, India Street, Dar-es-Salaam, Tanzania<br/><a href="tel:+255783394445">+255 783 394 445</a> · <a href="mailto:EktaDigital@outlook.com">EktaDigital@outlook.com</a></div>
</div></body></html>
